- name: copying the {{COMPONENT}} repo 
  ansible.builtin.copy:
     src: mysql.repo 
     dest: /etc/yum.repos.d/mysql.repo 
 
- name: Installing {{COMPONENT}} 
  ansible.builtin.package:
    name: 
       - mysql-community-server
       - MySQL-python
    state: present 
# We are installing MySQL-python as the task "Check the DB Password " needs that as per the error.

- name: Starting {{COMPONENT}} 
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes  

- name: Check the DB Password 
  community.mysql.mysql_info:
    login_user: root 
    login_password: RoboShop@1
  ignore_errors: yes
  register: mysql_stat 

- name: Reset Password Block 
  when: mysql_stat.failed 
  block:
    - name: Resetting the DB Paasword
      ansible.builtin.shell: grep "temporary password" /var/log/mysqld.log | awk '{print $NF}'
      register: DEFAULT_ROOT_PASSWORD      

    - name: Copy the SQL Password to tmp file 
      ansible.builtin.copy:
        src: rootpass.sql
        dest: /tmp/rootpass.sql

    - name: Resetting MySQL Password 
      ansible.builtin.shell: mysql  --connect-expired-password -uroot -p"{{DEFAULT_ROOT_PASSWORD.stdout}}"  < /tmp/rootpass.sql

- name: Check validate password plugin is removed or not 
  ansible.builtin.shell: echo show plugins | mysql -uroot -pRoboShop@1 | grep validate_password
  register: PLUG_INFO 
  ignore_errors: yes 

- name: Uninstall Password Validate Plugin  
  when: PLUG_INFO.rc == 0 
  block:
    - name: Copy the SQL Password to tmp file 
      ansible.builtin.copy:
        src: password-validate.sql
        dest: /tmp/password-validate.sql 
        
    - name: Uninstall the plugin 
      ansible.builtin.shell: mysql  --connect-expired-password -uroot -pRoboShop@1 < /tmp/password-validate.sql 
      
- name: Download and extracting {{COMPONENT}} Schema
  ansible.builtin.include_role:
    name: common 
    tasks_from: download 

- name: Load Schema 
  community.mysql.mysql_db:
    state: import
    name: all
    login_user: root 
    login_password: RoboShop@1
    target: /tmp/mysql-main/shipping.sql 

- name: Set-hostname 
  ansible.builtin.include_role:
    name: common 
    tasks_from: set-hostname 