ERLANG_URL: "https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm"
RABBITMQ_URL: "https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh"
APPUSER: roboshop